// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"microddd/application"
	"microddd/domain/repository"
	"microddd/infrastructure/db/dbcore"
	"microddd/infrastructure/db/dbinit"
	repository2 "microddd/infrastructure/repository"
	"microddd/interfaces/api"
)

// Injectors from wire.go:

func NewApp() (*repository.AuthFactory, error) {
	dbConfig, err := dbinit.LoadConfig()
	if err != nil {
		return nil, err
	}
	db, err := dbcore.Connect(dbConfig)
	if err != nil {
		return nil, err
	}
	authFactory := repository2.NewRepository(db)
	return authFactory, nil
}

// wire.go:

//go:generate wire
var providerSet = wire.NewSet(dbinit.LoadConfig, dbcore.Connect, repository2.NewRepository, application.NewApps, api.NewApi)
