// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"microddd/application"
	"microddd/infrastructure/db/dbcore"
	"microddd/infrastructure/db/dbinit"
	"microddd/infrastructure/repository"
	"microddd/interfaces/api"
	"microddd/interfaces/router"
)

// Injectors from wire.go:

func NewApp() (*router.Router, error) {
	dbConfig, err := dbinit.LoadConfig()
	if err != nil {
		return nil, err
	}
	db, err := dbcore.Connect(dbConfig)
	if err != nil {
		return nil, err
	}
	authFactory := repository.NewRepository(db)
	app := application.NewApps(authFactory)
	webApi := api.NewApi(app)
	routerRouter := &router.Router{
		WebApi: webApi,
	}
	return routerRouter, nil
}

// wire.go:

//go:generate wire
var providerSet = wire.NewSet(dbinit.LoadConfig, dbcore.Connect, repository.NewRepository, application.NewApps, api.NewApi, router.RouterSet)
